### ISSUE TITLE
示例的登录有点问题

### ISSUE THREAD

**Issue by 59799517** [sososdk/aliyunpan-flutter-sdk#3]
我的APPID appSecret  bundleId都是填写正确的

FlutterCredentials.pkce
FlutterCredentials.server
FlutterCredentials.secret
QrcodeCredentials.pkce
QrcodeCredentials.server
QrcodeCredentials.secret
这几种出现  client_id 不能为空的错误

```
E/chromium(30361): [ERROR:aw_browser_terminator.cc(166)] Renderer process (31102) crash detected (code -1).
E/flutter (30361): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ApiException: client_id 不能为空
E/flutter (30361): #0      DioExtension.send.<anonymous closure>.<anonymous closure> (package:aliyunpan_sdk/src/aliyunpan_client.dart:252:19)
E/flutter (30361): #1      DioExtension.send.<anonymous closure> (package:aliyunpan_sdk/src/aliyunpan_client.dart:255:14)
E/flutter (30361): #2      FutureExtensions.onError.onError (dart:async/future.dart:1082:25)
E/flutter (30361): #3      _RootZone.runBinary (dart:async/zone.dart:1666:54)
E/flutter (30361): #4      _FutureListener.handleError (dart:async/future_impl.dart:178:22)
E/flutter (30361): #5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:873:47)
E/flutter (30361): #6      Future._propagateToListeners (dart:async/future_impl.dart:894:13)
E/flutter (30361): #7      Future._completeError (dart:async/future_impl.dart:674:5)
E/flutter (30361): <asynchronous suspension>
```

WebCredentials.server
WebCredentials.secret
这两种调用 循环出现
```
D/ImageReaderSurfaceProducer(30361): ImageTextureEntry can't wait on the fence on Android < 33
I/chromium(30361): [INFO:CONSOLE(2)] "[record] window.goldlog not found push queue", source: https://g.alicdn.com/aliyun-drive-fe/aliyun-drive/4.12.8-auth/auth/bundle.js (2)
I/chromium(30361): [INFO:CONSOLE(1)] "[object Object]", source: https://g.alicdn.com/aliyun-drive-fe/aliyun-drive/4.12.8-auth/auth/321.bundle.js (1)
I/chromium(30361): [INFO:CONSOLE(2)] "%c [APLUS] -- APLUS INIT SUCCESS background:#3B82FE; padding: 4px; padding-right: 8px; border-radius: 4px; color: #fff;", source:  (2)
E/FrameEvents(30361): updateAcquireFence: Did not find frame.
E/FrameEvents(30361): updateAcquireFence: Did not find frame.
E/FrameEvents(30361): updateAcquireFence: Did not find frame.
E/FrameEvents(30361): updateAcquireFence: Did not find frame.
E/FrameEvents(30361): updateAcquireFence: Did not find frame.
E/FrameEvents(30361): updateAcquireFence: Did not find frame.
E/FrameEvents(30361): updateAcquireFence: Did not find frame.
```
这个错误

**Comment by osinn** [comment]
@sososdk 同样的问题，能否解决一下
